<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AppointmentController.php" was generated by ProBot AI.
* Date: 2/22/2025 12:59:11 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Appointment;
use App\Models\Patient;
use App\Models\Doctor;
use App\Models\Doctors\Doctor as DoctorsDoctor;
use App\Models\Patient\Patient as PatientPatient;
use App\Models\Status;
use App\Models\Payment_Status;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AppointmentController extends Controller{
	public function index(){
		$appointments = Appointment::paginate(10);
		return view("pages.erp.appointment.index",["appointments"=>$appointments]);
	}
	public function create(){
		return view("pages.erp.appointment.create",["patients"=>PatientPatient::all(),"doctors"=>DoctorsDoctor::all(),"status"=>Status::all(),"payment_statuss"=>Payment_Status::all()]);
	}
	public function store(Request $request){
		//Appointment::create($request->all());
		$appointment = new Appointment;
		$appointment->patient_id=$request->patient_id;
		$appointment->doctor_id=$request->doctor_id;
		$appointment->appointment_date=$request->appointment_date;
		$appointment->status_id=$request->status_id;
		$appointment->cancellation_reason=$request->cancellation_reason;
		$appointment->consultation_notes=$request->consultation_notes;
		$appointment->payment_status_id=$request->payment_status_id;
date_default_timezone_set("Asia/Dhaka");
		$appointment->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$appointment->updated_at=date('Y-m-d H:i:s');

		$appointment->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$appointment = Appointment::find($id);
		return view("pages.erp.appointment.show",["appointment"=>$appointment]);
	}
	public function edit(Appointment $appointment){
		return view("pages.erp.appointment.edit",["appointment"=>$appointment,"patients"=>Patient::all(),"doctors"=>Doctor::all(),"status"=>Status::all(),"payment_statuss"=>Payment_Status::all()]);
	}
	public function update(Request $request,Appointment $appointment){
		//Appointment::update($request->all());
		$appointment = Appointment::find($appointment->id);
		$appointment->patient_id=$request->patient_id;
		$appointment->doctor_id=$request->doctor_id;
		$appointment->appointment_date=$request->appointment_date;
		$appointment->status_id=$request->status_id;
		$appointment->cancellation_reason=$request->cancellation_reason;
		$appointment->consultation_notes=$request->consultation_notes;
		$appointment->payment_status_id=$request->payment_status_id;
date_default_timezone_set("Asia/Dhaka");
		$appointment->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$appointment->updated_at=date('Y-m-d H:i:s');

		$appointment->save();

		return redirect()->route("appointments.index")->with('success','Updated Successfully.');
	}
	public function destroy(Appointment $appointment){
		$appointment->delete();
		return redirect()->route("appointments.index")->with('success', 'Deleted Successfully.');
	}
}
?>
