<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ConsultationController.php" was generated by ProBot AI.
* Date: 2/22/2025 10:07:16 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Consultation;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ConsultationController extends Controller{
	public function index(){
		$consultations = Consultation::get();
		return view("pages.erp.consultation.index",["consultations"=>$consultations]);
	}
	public function create(){
		return view("pages.erp.consultation.create",[]);
	}
	public function store(Request $request){
		//Consultation::create($request->all());
		$consultation = new Consultation;
		$consultation->id=$request->id;
		$consultation->appointment_id=$request->appointment_id;
		$consultation->symptoms=$request->symptoms;
		$consultation->diagnosis=$request->diagnosis;
		$consultation->prescription=$request->prescription;
		$consultation->consultation_notes=$request->consultation_notes;
date_default_timezone_set("Asia/Dhaka");
		$consultation->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$consultation->updated_at=date('Y-m-d H:i:s');

		$consultation->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$consultation = Consultation::find($id);
		return view("pages.erp.consultation.show",["consultation"=>$consultation]);
	}
	public function edit(Consultation $consultation){
		return view("pages.erp.consultation.edit",["consultation"=>$consultation,]);
	}
	public function update(Request $request,Consultation $consultation){
		//Consultation::update($request->all());
		$consultation = Consultation::find($consultation->id);
		$consultation->id=$request->id;
		$consultation->appointment_id=$request->appointment_id;
		$consultation->symptoms=$request->symptoms;
		$consultation->diagnosis=$request->diagnosis;
		$consultation->prescription=$request->prescription;
		$consultation->consultation_notes=$request->consultation_notes;
date_default_timezone_set("Asia/Dhaka");
		$consultation->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$consultation->updated_at=date('Y-m-d H:i:s');

		$consultation->save();

		return redirect()->route("consultations.index")->with('success','Updated Successfully.');
	}
	public function destroy(Consultation $consultation){
		$consultation->delete();
		return redirect()->route("consultations.index")->with('success', 'Deleted Successfully.');
	}
}
?>
