<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingservice/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:44 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage BillingService')
@section('style')


@endsection
@section('page')
<a href="{{route('billingservices.create')}}">New BillingService</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Billing Id</th>
			<th>Service Id</th>
			<th>Price</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($billingservices as $billingservice)
		<tr>
			<td>{{$billingservice->id}}</td>
			<td>{{$billingservice->billing_id}}</td>
			<td>{{$billingservice->service_id}}</td>
			<td>{{$billingservice->price}}</td>
			<td>{{$billingservice->created_at}}</td>
			<td>{{$billingservice->updated_at}}</td>

			<td>
			<form action = "{{route('billingservices.destroy',$billingservice->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('billingservices.show',$billingservice->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('billingservices.edit',$billingservice->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
