<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingservice/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:44 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show BillingService')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('billingservices.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$billingservice->id}}</td></tr>
		<tr><th>Billing Id</th><td>{{$billingservice->billing_id}}</td></tr>
		<tr><th>Service Id</th><td>{{$billingservice->service_id}}</td></tr>
		<tr><th>Price</th><td>{{$billingservice->price}}</td></tr>
		<tr><th>Created At</th><td>{{$billingservice->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$billingservice->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
