<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/medicine/_edit.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:53 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Medicine')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('medicines.index')}}">Manage</a>
<form action="{{route('medicines.update',$medicine)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$medicine->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="category" class="col-sm-2 col-form-label">Category</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="category" value="{{$medicine->category}}" id="category" placeholder="Category">
	</div>
</div>
<div class="row mb-3">
	<label for="dosage" class="col-sm-2 col-form-label">Dosage</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="dosage" value="{{$medicine->dosage}}" id="dosage" placeholder="Dosage">
	</div>
</div>
<div class="row mb-3">
	<label for="strength" class="col-sm-2 col-form-label">Strength</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="strength" value="{{$medicine->strength}}" id="strength" placeholder="Strength">
	</div>
</div>
<div class="row mb-3">
	<label for="manufacturer" class="col-sm-2 col-form-label">Manufacturer</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="manufacturer" value="{{$medicine->manufacturer}}" id="manufacturer" placeholder="Manufacturer">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$medicine->price}}" id="price" placeholder="Price">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
