<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/medicine/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:53 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Medicine')
@section('style')


@endsection
@section('page')
<a href="{{route('medicines.create')}}">New Medicine</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Category</th>
			<th>Dosage</th>
			<th>Strength</th>
			<th>Manufacturer</th>
			<th>Price</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($medicines as $medicine)
		<tr>
			<td>{{$medicine->id}}</td>
			<td>{{$medicine->name}}</td>
			<td>{{$medicine->category}}</td>
			<td>{{$medicine->dosage}}</td>
			<td>{{$medicine->strength}}</td>
			<td>{{$medicine->manufacturer}}</td>
			<td>{{$medicine->price}}</td>
			<td>{{$medicine->created_at}}</td>
			<td>{{$medicine->updated_at}}</td>

			<td>
			<form action = "{{route('medicines.destroy',$medicine->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('medicines.show',$medicine->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('medicines.edit',$medicine->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
