<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/medicine/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:53 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Medicine')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('medicines.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$medicine->id}}</td></tr>
		<tr><th>Name</th><td>{{$medicine->name}}</td></tr>
		<tr><th>Category</th><td>{{$medicine->category}}</td></tr>
		<tr><th>Dosage</th><td>{{$medicine->dosage}}</td></tr>
		<tr><th>Strength</th><td>{{$medicine->strength}}</td></tr>
		<tr><th>Manufacturer</th><td>{{$medicine->manufacturer}}</td></tr>
		<tr><th>Price</th><td>{{$medicine->price}}</td></tr>
		<tr><th>Created At</th><td>{{$medicine->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$medicine->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
