<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingbed/_create.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:45 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create BillingBed')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('billingbeds.index')}}">Manage</a>
<form action="{{route('billingbeds.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="billing_id" class="col-sm-2 col-form-label">Billing</label>
	<div class="col-sm-10">
		<select class="form-control" name="billing_id" id="billing_id">
			@foreach($billings as $billing)
				<option value="{{$billing->id}}">{{$billing->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="bed_id" class="col-sm-2 col-form-label">Bed</label>
	<div class="col-sm-10">
		<select class="form-control" name="bed_id" id="bed_id">
			@foreach($beds as $bed)
				<option value="{{$bed->id}}">{{$bed->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" id="price" placeholder="Price">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
