<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billinglabtest/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:46 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage BillingLabTest')
@section('style')


@endsection
@section('page')
<a href="{{route('billinglabtests.create')}}">New BillingLabTest</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Billing Id</th>
			<th>Lab Test Id</th>
			<th>Price</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($billinglabtests as $billinglabtest)
		<tr>
			<td>{{$billinglabtest->id}}</td>
			<td>{{$billinglabtest->billing_id}}</td>
			<td>{{$billinglabtest->lab_test_id}}</td>
			<td>{{$billinglabtest->price}}</td>
			<td>{{$billinglabtest->created_at}}</td>
			<td>{{$billinglabtest->updated_at}}</td>

			<td>
			<form action = "{{route('billinglabtests.destroy',$billinglabtest->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('billinglabtests.show',$billinglabtest->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('billinglabtests.edit',$billinglabtest->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
