<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/consultation/_index.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 10:07:20 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Consultation')
@section('style')


@endsection
@section('page')
<a href="{{route('consultations.create')}}">New Consultation</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Appointment Id</th>
			<th>Symptoms</th>
			<th>Diagnosis</th>
			<th>Prescription</th>
			<th>Consultation Notes</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($consultations as $consultation)
		<tr>
			<td>{{$consultation->id}}</td>
			<td>{{$consultation->appointment_id}}</td>
			<td>{{$consultation->symptoms}}</td>
			<td>{{$consultation->diagnosis}}</td>
			<td>{{$consultation->prescription}}</td>
			<td>{{$consultation->consultation_notes}}</td>
			<td>{{$consultation->created_at}}</td>
			<td>{{$consultation->updated_at}}</td>

			<td>
			<form action = "{{route('consultations.destroy',$consultation->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('consultations.show',$consultation->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('consultations.edit',$consultation->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
