<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/service/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:55 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Service')
@section('style')


@endsection
@section('page')
<a href="{{route('services.create')}}">New Service</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Price</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($services as $service)
		<tr>
			<td>{{$service->id}}</td>
			<td>{{$service->name}}</td>
			<td>{{$service->price}}</td>
			<td>{{$service->created_at}}</td>
			<td>{{$service->updated_at}}</td>

			<td>
			<form action = "{{route('services.destroy',$service->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('services.show',$service->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('services.edit',$service->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
