<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/service/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:55 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Service')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('services.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$service->id}}</td></tr>
		<tr><th>Name</th><td>{{$service->name}}</td></tr>
		<tr><th>Price</th><td>{{$service->price}}</td></tr>
		<tr><th>Created At</th><td>{{$service->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$service->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
