<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/appointment/_edit.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 12:59:16 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Appointment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('appointments.index')}}">Manage</a>
<form action="{{route('appointments.update',$appointment)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="patient_id" class="col-sm-2 col-form-label">Patient</label>
	<div class="col-sm-10">
		<select class="form-control" name="patient_id" id="patient_id">
			@foreach($patients as $patient)
				@if($patient->id==$appointment->patient_id)
					<option value="{{$patient->id}}" selected>{{$patient->name}}</option>
				@else
					<option value="{{$patient->id}}">{{$patient->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="doctor_id" class="col-sm-2 col-form-label">Doctor</label>
	<div class="col-sm-10">
		<select class="form-control" name="doctor_id" id="doctor_id">
			@foreach($doctors as $doctor)
				@if($doctor->id==$appointment->doctor_id)
					<option value="{{$doctor->id}}" selected>{{$doctor->name}}</option>
				@else
					<option value="{{$doctor->id}}">{{$doctor->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="status_id" class="col-sm-2 col-form-label">Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="status_id" id="status_id">
			@foreach($status as $status)
				@if($status->id==$appointment->status_id)
					<option value="{{$status->id}}" selected>{{$status->name}}</option>
				@else
					<option value="{{$status->id}}">{{$status->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="cancellation_reason" class="col-sm-2 col-form-label">Cancellation Reason</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="cancellation_reason" value="{{$appointment->cancellation_reason}}" id="cancellation_reason" placeholder="Cancellation Reason">
	</div>
</div>
<div class="row mb-3">
	<label for="consultation_notes" class="col-sm-2 col-form-label">Consultation Notes</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="consultation_notes" value="{{$appointment->consultation_notes}}" id="consultation_notes" placeholder="Consultation Notes">
	</div>
</div>
<div class="row mb-3">
	<label for="payment_status_id" class="col-sm-2 col-form-label">Payment_Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="payment_status_id" id="payment_status_id">
			@foreach($payment_statuss as $payment_status)
				@if($payment_status->id==$appointment->payment_status_id)
					<option value="{{$payment_status->id}}" selected>{{$payment_status->name}}</option>
				@else
					<option value="{{$payment_status->id}}">{{$payment_status->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
