<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/appointment/_index.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 12:59:16 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Appointment')
@section('style')


@endsection
@section('page')
<a href="{{route('appointments.create')}}">New Appointment</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Patient Id</th>
			<th>Doctor Id</th>
			<th>Appointment Date</th>
			<th>Status Id</th>
			<th>Cancellation Reason</th>
			<th>Consultation Notes</th>
			<th>Payment Status Id</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($appointments as $appointment)
		<tr>
			<td>{{$appointment->id}}</td>
			<td>{{$appointment->patient_id}}</td>
			<td>{{$appointment->doctor_id}}</td>
			<td>{{$appointment->appointment_date}}</td>
			<td>{{$appointment->status_id}}</td>
			<td>{{$appointment->cancellation_reason}}</td>
			<td>{{$appointment->consultation_notes}}</td>
			<td>{{$appointment->payment_status_id}}</td>
			<td>{{$appointment->created_at}}</td>
			<td>{{$appointment->updated_at}}</td>

			<td>
			<form action = "{{route('appointments.destroy',$appointment->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('appointments.show',$appointment->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('appointments.edit',$appointment->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
