<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/appointment/_show.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 12:59:16 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Appointment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('appointments.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$appointment->id}}</td></tr>
		<tr><th>Patient Id</th><td>{{$appointment->patient_id}}</td></tr>
		<tr><th>Doctor Id</th><td>{{$appointment->doctor_id}}</td></tr>
		<tr><th>Appointment Date</th><td>{{$appointment->appointment_date}}</td></tr>
		<tr><th>Status Id</th><td>{{$appointment->status_id}}</td></tr>
		<tr><th>Cancellation Reason</th><td>{{$appointment->cancellation_reason}}</td></tr>
		<tr><th>Consultation Notes</th><td>{{$appointment->consultation_notes}}</td></tr>
		<tr><th>Payment Status Id</th><td>{{$appointment->payment_status_id}}</td></tr>
		<tr><th>Created At</th><td>{{$appointment->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$appointment->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
