<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billing/_create.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:40 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Billing')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('billings.index')}}">Manage</a>
<form action="{{route('billings.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="patient_id" class="col-sm-2 col-form-label">Patient</label>
	<div class="col-sm-10">
		<select class="form-control" name="patient_id" id="patient_id">
			@foreach($patients as $patient)
				<option value="{{$patient->id}}">{{$patient->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="appointment_id" class="col-sm-2 col-form-label">Appointment</label>
	<div class="col-sm-10">
		<select class="form-control" name="appointment_id" id="appointment_id">
			@foreach($appointments as $appointment)
				<option value="{{$appointment->id}}">{{$appointment->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="total_amount" class="col-sm-2 col-form-label">Total Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="total_amount" id="total_amount" placeholder="Total Amount">
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" id="discount" placeholder="Discount">
	</div>
</div>
<div class="row mb-3">
	<label for="tax" class="col-sm-2 col-form-label">Tax</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="tax" id="tax" placeholder="Tax">
	</div>
</div>
<div class="row mb-3">
	<label for="paid_amount" class="col-sm-2 col-form-label">Paid Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="paid_amount" id="paid_amount" placeholder="Paid Amount">
	</div>
</div>
<div class="row mb-3">
	<label for="balance_amount" class="col-sm-2 col-form-label">Balance Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="balance_amount" id="balance_amount" placeholder="Balance Amount">
	</div>
</div>
<div class="row mb-3">
	<label for="payment_status_id" class="col-sm-2 col-form-label">Payment_Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="payment_status_id" id="payment_status_id">
			@foreach($payment_statuss as $payment_status)
				<option value="{{$payment_status->id}}">{{$payment_status->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="payment_mode" class="col-sm-2 col-form-label">Payment Mode</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="payment_mode" id="payment_mode" placeholder="Payment Mode">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
