<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bedassignment/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:39 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage BedAssignment')
@section('style')


@endsection
@section('page')
<a href="{{route('bedassignments.create')}}">New BedAssignment</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Bed Id</th>
			<th>Patient Id</th>
			<th>Assigned At</th>
			<th>Discharged At</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($bedassignments as $bedassignment)
		<tr>
			<td>{{$bedassignment->id}}</td>
			<td>{{$bedassignment->bed_id}}</td>
			<td>{{$bedassignment->patient_id}}</td>
			<td>{{$bedassignment->assigned_at}}</td>
			<td>{{$bedassignment->discharged_at}}</td>
			<td>{{$bedassignment->created_at}}</td>
			<td>{{$bedassignment->updated_at}}</td>

			<td>
			<form action = "{{route('bedassignments.destroy',$bedassignment->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('bedassignments.show',$bedassignment->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('bedassignments.edit',$bedassignment->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
