<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bedassignment/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:39 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show BedAssignment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('bedassignments.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$bedassignment->id}}</td></tr>
		<tr><th>Bed Id</th><td>{{$bedassignment->bed_id}}</td></tr>
		<tr><th>Patient Id</th><td>{{$bedassignment->patient_id}}</td></tr>
		<tr><th>Assigned At</th><td>{{$bedassignment->assigned_at}}</td></tr>
		<tr><th>Discharged At</th><td>{{$bedassignment->discharged_at}}</td></tr>
		<tr><th>Created At</th><td>{{$bedassignment->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$bedassignment->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
