<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingmedicine/_edit.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:43 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit BillingMedicine')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('billingmedicines.index')}}">Manage</a>
<form action="{{route('billingmedicines.update',$billingmedicine)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="billing_id" class="col-sm-2 col-form-label">Billing</label>
	<div class="col-sm-10">
		<select class="form-control" name="billing_id" id="billing_id">
			@foreach($billings as $billing)
				@if($billing->id==$billingmedicine->billing_id)
					<option value="{{$billing->id}}" selected>{{$billing->name}}</option>
				@else
					<option value="{{$billing->id}}">{{$billing->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="medicine_id" class="col-sm-2 col-form-label">Medicine</label>
	<div class="col-sm-10">
		<select class="form-control" name="medicine_id" id="medicine_id">
			@foreach($medicines as $medicine)
				@if($medicine->id==$billingmedicine->medicine_id)
					<option value="{{$medicine->id}}" selected>{{$medicine->name}}</option>
				@else
					<option value="{{$medicine->id}}">{{$medicine->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" value="{{$billingmedicine->quantity}}" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$billingmedicine->price}}" id="price" placeholder="Price">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
