<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingmedicine/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:43 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage BillingMedicine')
@section('style')


@endsection
@section('page')
<a href="{{route('billingmedicines.create')}}">New BillingMedicine</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Billing Id</th>
			<th>Medicine Id</th>
			<th>Quantity</th>
			<th>Price</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($billingmedicines as $billingmedicine)
		<tr>
			<td>{{$billingmedicine->id}}</td>
			<td>{{$billingmedicine->billing_id}}</td>
			<td>{{$billingmedicine->medicine_id}}</td>
			<td>{{$billingmedicine->quantity}}</td>
			<td>{{$billingmedicine->price}}</td>
			<td>{{$billingmedicine->created_at}}</td>
			<td>{{$billingmedicine->updated_at}}</td>

			<td>
			<form action = "{{route('billingmedicines.destroy',$billingmedicine->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('billingmedicines.show',$billingmedicine->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('billingmedicines.edit',$billingmedicine->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
