<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingmedicine/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:43 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show BillingMedicine')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('billingmedicines.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$billingmedicine->id}}</td></tr>
		<tr><th>Billing Id</th><td>{{$billingmedicine->billing_id}}</td></tr>
		<tr><th>Medicine Id</th><td>{{$billingmedicine->medicine_id}}</td></tr>
		<tr><th>Quantity</th><td>{{$billingmedicine->quantity}}</td></tr>
		<tr><th>Price</th><td>{{$billingmedicine->price}}</td></tr>
		<tr><th>Created At</th><td>{{$billingmedicine->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$billingmedicine->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
