<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/ward/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:15:40 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.backend.main')
@section('title','Show Ward')
@section('style')


@endsection
@section('page-content')
<a class='btn btn-success' href="{{route('wards.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$ward->id}}</td></tr>
		<tr><th>Name</th><td>{{$ward->name}}</td></tr>
		<tr><th>Type</th><td>{{$ward->type}}</td></tr>
		<tr><th>Created At</th><td>{{$ward->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$ward->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
