<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/doctoravailability/_create.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 12:05:37 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.backend.main')
@section('title','Create DoctorAvailability')
@section('style')


@endsection
@section('page-content')
<a class='btn btn-success' href="{{route('doctoravailabilitys.index')}}">Manage</a>
<form action="{{route('doctoravailabilitys.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="doctor_id" class="col-sm-2 col-form-label">Doctor</label>
	<div class="col-sm-10">
		<select class="form-control" name="doctor_id" id="doctor_id">
			@foreach($doctors as $doctor)
				<option value="{{$doctor->id}}">{{$doctor->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="day" class="col-sm-2 col-form-label">Day</label>
	<div class="col-sm-10">
		<input type = "day" class="form-control" name="day" id="day" placeholder="Day">
	</div>
</div>
<div class="row mb-3">
	<label for="start_time" class="col-sm-2 col-form-label">Start Time</label>
	<div class="col-sm-10">
		<input type = "time" class="form-control" name="start_time" id="start_time" placeholder="Start Time">
	</div>
</div>
<div class="row mb-3">
	<label for="end_time" class="col-sm-2 col-form-label">End Time</label>
	<div class="col-sm-10">
		<input type = "time" class="form-control" name="end_time" id="end_time" placeholder="End Time">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
