<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/doctoravailability/_edit.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 12:05:37 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.backend.main')
@section('title','Edit DoctorAvailability')
@section('style')


@endsection
@section('page-content')
<a class='btn btn-success' href="{{route('doctoravailabilitys.index')}}">Manage</a>
<form action="{{route('doctoravailabilitys.update',$doctoravailability)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="doctor_id" class="col-sm-2 col-form-label">Doctor</label>
	<div class="col-sm-10">
		<select class="form-control" name="doctor_id" id="doctor_id">
			@foreach($doctors as $doctor)
				@if($doctor->id==$doctoravailability->doctor_id)
					<option value="{{$doctor->id}}" selected>{{$doctor->name}}</option>
				@else
					<option value="{{$doctor->id}}">{{$doctor->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="day" class="col-sm-2 col-form-label">Day</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="day" value="{{$doctoravailability->day}}" id="day" placeholder="Day">
	</div>
</div>
<div class="row mb-3">
	<label for="start_time" class="col-sm-2 col-form-label">Start Time</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="start_time" value="{{$doctoravailability->start_time}}" id="start_time" placeholder="Start Time">
	</div>
</div>
<div class="row mb-3">
	<label for="end_time" class="col-sm-2 col-form-label">End Time</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="end_time" value="{{$doctoravailability->end_time}}" id="end_time" placeholder="End Time">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
