<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/doctoravailability/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 12:05:37 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layouts.backend.main')
@section('title','Manage DoctorAvailability')
@section('style')


@endsection
@section('page-content')
<a href="{{route('doctoravailabilitys.create')}}">New DoctorAvailability</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Doctor Id</th>
			<th>Day</th>
			<th>Start Time</th>
			<th>End Time</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($doctoravailabilitys as $doctoravailability)
		<tr>
			<td>{{$doctoravailability->id}}</td>
			<td>{{$doctoravailability->doctor_id}}</td>
			<td>{{$doctoravailability->day}}</td>
			<td>{{$doctoravailability->start_time}}</td>
			<td>{{$doctoravailability->end_time}}</td>
			<td>{{$doctoravailability->created_at}}</td>
			<td>{{$doctoravailability->updated_at}}</td>

			<td>
			<form action = "{{route('doctoravailabilitys.destroy',$doctoravailability->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('doctoravailabilitys.show',$doctoravailability->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('doctoravailabilitys.edit',$doctoravailability->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
