<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PaymentStatus.php" was generated by ProBot AI.
* Date: 2/22/2025 4:50:31 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PaymentStatus extends Model{

    protected $table = 'payment_statuss';

}
?>
