<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bed/_create.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:35 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Bed')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('beds.index')}}">Manage</a>
<form action="{{route('beds.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="bed_number" class="col-sm-2 col-form-label">Bed Number</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="bed_number" id="bed_number" placeholder="Bed Number">
	</div>
</div>
<div class="row mb-3">
	<label for="ward_id" class="col-sm-2 col-form-label">Ward</label>
	<div class="col-sm-10">
		<select class="form-control" name="ward_id" id="ward_id">
			@foreach($wards as $ward)
				<option value="{{$ward->id}}">{{$ward->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="status_id" class="col-sm-2 col-form-label">Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="status_id" id="status_id">
			@foreach($status as $status)
				<option value="{{$status->id}}">{{$status->name}}</option>
			@endforeach
		</select>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
