<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bed/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:35 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Bed')
@section('style')


@endsection
@section('page')
<a href="{{route('beds.create')}}">New Bed</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Bed Number</th>
			<th>Ward Id</th>
			<th>Status Id</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($beds as $bed)
		<tr>
			<td>{{$bed->id}}</td>
			<td>{{$bed->bed_number}}</td>
			<td>{{$bed->ward_id}}</td>
			<td>{{$bed->status_id}}</td>
			<td>{{$bed->created_at}}</td>
			<td>{{$bed->updated_at}}</td>

			<td>
			<form action = "{{route('beds.destroy',$bed->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('beds.show',$bed->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('beds.edit',$bed->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
