<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bed/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:35 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Bed')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('beds.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$bed->id}}</td></tr>
		<tr><th>Bed Number</th><td>{{$bed->bed_number}}</td></tr>
		<tr><th>Ward Id</th><td>{{$bed->ward_id}}</td></tr>
		<tr><th>Status Id</th><td>{{$bed->status_id}}</td></tr>
		<tr><th>Created At</th><td>{{$bed->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$bed->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
