<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/ward/_edit.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:52:38 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Ward')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('wards.index')}}">Manage</a>
<form action="{{route('wards.update',$ward)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$ward->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="type" class="col-sm-2 col-form-label">Type</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="type" value="{{$ward->type}}" id="type" placeholder="Type">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
