<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/ward/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:52:38 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Ward')
@section('style')


@endsection
@section('page')
<a href="{{route('wards.create')}}">New Ward</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Type</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($wards as $ward)
		<tr>
			<td>{{$ward->id}}</td>
			<td>{{$ward->name}}</td>
			<td>{{$ward->type}}</td>
			<td>{{$ward->created_at}}</td>
			<td>{{$ward->updated_at}}</td>

			<td>
			<form action = "{{route('wards.destroy',$ward->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('wards.show',$ward->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('wards.edit',$ward->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
