<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingconsultation/_create.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:42 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create BillingConsultation')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('billingconsultations.index')}}">Manage</a>
<form action="{{route('billingconsultations.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="billing_id" class="col-sm-2 col-form-label">Billing</label>
	<div class="col-sm-10">
		<select class="form-control" name="billing_id" id="billing_id">
			@foreach($billings as $billing)
				<option value="{{$billing->id}}">{{$billing->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="consultation_id" class="col-sm-2 col-form-label">Consultation</label>
	<div class="col-sm-10">
		<select class="form-control" name="consultation_id" id="consultation_id">
			@foreach($consultations as $consultation)
				<option value="{{$consultation->id}}">{{$consultation->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="consultation_fee" class="col-sm-2 col-form-label">Consultation Fee</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="consultation_fee" id="consultation_fee" placeholder="Consultation Fee">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
