<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingconsultation/_index.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:42 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage BillingConsultation')
@section('style')


@endsection
@section('page')
<a href="{{route('billingconsultations.create')}}">New BillingConsultation</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Billing Id</th>
			<th>Consultation Id</th>
			<th>Consultation Fee</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($billingconsultations as $billingconsultation)
		<tr>
			<td>{{$billingconsultation->id}}</td>
			<td>{{$billingconsultation->billing_id}}</td>
			<td>{{$billingconsultation->consultation_id}}</td>
			<td>{{$billingconsultation->consultation_fee}}</td>
			<td>{{$billingconsultation->created_at}}</td>
			<td>{{$billingconsultation->updated_at}}</td>

			<td>
			<form action = "{{route('billingconsultations.destroy',$billingconsultation->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('billingconsultations.show',$billingconsultation->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('billingconsultations.edit',$billingconsultation->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
