<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/billingconsultation/_show.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:49:42 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show BillingConsultation')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('billingconsultations.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$billingconsultation->id}}</td></tr>
		<tr><th>Billing Id</th><td>{{$billingconsultation->billing_id}}</td></tr>
		<tr><th>Consultation Id</th><td>{{$billingconsultation->consultation_id}}</td></tr>
		<tr><th>Consultation Fee</th><td>{{$billingconsultation->consultation_fee}}</td></tr>
		<tr><th>Created At</th><td>{{$billingconsultation->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$billingconsultation->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
