<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentstatus/_create.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 4:50:31 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create PaymentStatus')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('paymentstatuss.index')}}">Manage</a>
<form action="{{route('paymentstatuss.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
